/**
 * Canonical skill → aliases map.
 * The canonical name is what gets stored in `detectedSkills`.
 * Aliases are matched case-insensitively with word-boundary checks.
 */
export const SKILL_ALIASES: Record<string, string[]> = {
  // ── Languages ──
  JavaScript: ["javascript", "js", "ecmascript", "es6", "es2015", "es2020"],
  TypeScript: ["typescript", "ts"],
  Python: ["python3", "python2", "py"],
  Java: ["java8", "java11", "java17", "java21", "jdk", "jre"],
  "C#": ["csharp", "c sharp", "c-sharp", "dotnet", "dot net", ".net", ".net core", "asp.net"],
  "C++": ["cpp", "cplusplus", "c plus plus"],
  C: [],
  Go: ["golang"],
  Rust: ["rustlang"],
  Swift: ["swiftui", "swift ui"],
  Kotlin: ["kotlin"],
  Ruby: ["ruby"],
  PHP: ["php7", "php8"],
  Dart: ["dart"],
  Scala: ["scala"],
  R: ["r language", "rlang"],
  Lua: ["lua"],
  Perl: ["perl"],
  Elixir: ["elixir"],
  Clojure: ["clojure"],
  Haskell: ["haskell"],
  Shell: ["bash", "zsh", "shell scripting", "powershell"],
  SQL: ["structured query language", "t-sql", "pl/sql", "plsql", "tsql"],
  Solidity: ["solidity", "smart contracts"],

  // ── Frontend Frameworks ──
  React: ["reactjs", "react.js", "react js", "react native"],
  "Next.js": ["nextjs", "next js", "next.js"],
  Vue: ["vuejs", "vue.js", "vue js", "vue2", "vue3"],
  Nuxt: ["nuxtjs", "nuxt.js", "nuxt js"],
  Angular: ["angularjs", "angular.js", "angular js", "angular 2", "angular 17"],
  Svelte: ["sveltekit", "svelte kit"],
  Remix: ["remixjs", "remix.js"],
  Astro: ["astrojs", "astro.js"],
  Gatsby: ["gatsbyjs", "gatsby.js"],
  jQuery: ["jquery"],
  Ember: ["emberjs", "ember.js"],

  // ── Backend Frameworks ──
  "Node.js": ["nodejs", "node js", "node.js"],
  Express: ["expressjs", "express.js"],
  NestJS: ["nestjs", "nest.js"],
  Fastify: ["fastify"],
  Hono: ["hono"],
  Django: ["django rest", "drf", "django rest framework"],
  Flask: ["flask api"],
  FastAPI: ["fastapi", "fast api"],
  "Ruby on Rails": ["rails", "ror", "ruby on rails"],
  Laravel: ["laravel"],
  Symfony: ["symfony"],
  "Spring Boot": ["spring boot", "springboot", "spring framework", "spring"],
  ASP: ["asp.net core", "asp.net mvc"],
  Gin: ["gin-gonic", "gin gonic"],
  Fiber: ["gofiber", "go fiber"],

  // ── CSS / UI ──
  CSS: ["css3", "cascading style sheets"],
  Sass: ["scss", "sass"],
  Less: ["less css", "lessjs"],
  "Tailwind CSS": ["tailwindcss", "tailwind css", "tailwind"],
  Bootstrap: ["bootstrap 5", "bootstrap5"],
  "Material UI": ["mui", "material-ui", "material design"],
  "Chakra UI": ["chakra"],
  "Ant Design": ["antd", "ant design"],
  "Styled Components": ["styled-components", "styled components"],
  HTML: ["html5"],
  "Framer Motion": ["framer motion", "framer-motion"],
  Radix: ["radix ui", "radix-ui"],
  "shadcn/ui": ["shadcn"],

  // ── State Management ──
  Redux: ["redux toolkit", "rtk", "rtk query"],
  MobX: ["mobx"],
  Zustand: ["zustand"],
  Recoil: ["recoil"],
  Jotai: ["jotai"],
  "React Query": ["tanstack query", "react-query", "tanstack"],

  // ── Databases ──
  PostgreSQL: ["postgres", "psql", "postgresql"],
  MySQL: ["mariadb", "mysql"],
  MongoDB: ["mongo", "mongoose"],
  Redis: ["redis cache", "redis"],
  SQLite: ["sqlite3", "sqlite"],
  "SQL Server": ["mssql", "microsoft sql server", "ms sql"],
  Oracle: ["oracle db", "oracle database"],
  DynamoDB: ["dynamo db", "dynamodb"],
  Cassandra: ["apache cassandra"],
  CouchDB: ["couchdb", "couch db"],
  Neo4j: ["neo4j"],
  Supabase: ["supabase"],
  Firebase: ["firestore", "firebase auth", "firebase realtime"],
  PlanetScale: ["planetscale"],
  Neon: ["neon db", "neon postgres"],

  // ── ORMs / Query Builders ──
  Prisma: ["prisma orm", "prisma"],
  Drizzle: ["drizzle orm", "drizzle"],
  TypeORM: ["typeorm"],
  Sequelize: ["sequelize"],
  Knex: ["knex.js", "knexjs"],
  SQLAlchemy: ["sqlalchemy", "sql alchemy"],
  Hibernate: ["hibernate"],

  // ── APIs ──
  REST: ["restful", "rest api", "restful api", "rest apis"],
  GraphQL: ["graphql", "gql"],
  gRPC: ["grpc", "protobuf", "protocol buffers"],
  tRPC: ["trpc"],
  WebSocket: ["websockets", "ws", "socket.io", "socketio"],
  OpenAPI: ["swagger", "openapi"],
  Postman: ["postman"],
  Insomnia: ["insomnia api"],
  Apollo: ["apollo client", "apollo server", "apollo graphql"],

  // ── Cloud & Infrastructure ──
  AWS: ["amazon web services", "amazon aws"],
  Azure: ["microsoft azure", "azure cloud"],
  GCP: ["google cloud", "google cloud platform"],
  "AWS S3": ["s3", "simple storage service"],
  "AWS EC2": ["ec2", "elastic compute"],
  "AWS Lambda": ["lambda", "aws lambda"],
  "AWS ECS": ["ecs", "elastic container service"],
  "AWS RDS": ["rds", "relational database service"],
  "AWS SQS": ["sqs", "simple queue service"],
  "AWS SNS": ["sns", "simple notification service"],
  "Azure Functions": ["azure functions"],
  "Cloud Functions": ["google cloud functions"],
  Cloudflare: ["cloudflare workers", "cloudflare"],
  DigitalOcean: ["digital ocean"],
  Linode: ["linode"],

  // ── DevOps & CI/CD ──
  Docker: ["dockerfile", "docker compose", "docker-compose", "containerization"],
  Kubernetes: ["k8s", "kube", "kubectl", "helm"],
  Terraform: ["tf", "hcl", "infrastructure as code"],
  Ansible: ["ansible"],
  Pulumi: ["pulumi"],
  Jenkins: ["jenkins ci"],
  "GitHub Actions": ["github actions", "gh actions"],
  "GitLab CI": ["gitlab ci", "gitlab ci/cd"],
  CircleCI: ["circle ci", "circleci"],
  TravisCI: ["travis ci", "travisci"],
  ArgoCD: ["argocd", "argo cd"],
  "CI/CD": ["cicd", "continuous integration", "continuous deployment", "continuous delivery"],
  Nginx: ["nginx"],
  Apache: ["apache httpd", "apache server"],
  Caddy: ["caddy"],
  PM2: ["pm2"],

  // ── Version Control ──
  Git: ["git"],
  GitHub: ["github"],
  GitLab: ["gitlab"],
  Bitbucket: ["bitbucket"],

  // ── Monitoring & Observability ──
  Datadog: ["datadog"],
  Grafana: ["grafana"],
  Prometheus: ["prometheus"],
  Sentry: ["sentry"],
  "New Relic": ["new relic", "newrelic"],
  "ELK Stack": ["elk", "elastic stack"],
  Elasticsearch: ["elastic", "elasticsearch"],
  Logstash: ["logstash"],
  Kibana: ["kibana"],
  PagerDuty: ["pagerduty"],

  // ── Testing ──
  Jest: ["jest testing", "jest"],
  Vitest: ["vitest"],
  Mocha: ["mocha"],
  Chai: ["chai"],
  Cypress: ["cypress.io", "cypress"],
  Playwright: ["playwright testing", "playwright"],
  Selenium: ["selenium webdriver", "selenium"],
  "React Testing Library": ["testing library", "rtl"],
  Puppeteer: ["puppeteer"],
  pytest: ["pytest"],
  JUnit: ["junit"],
  "Unit Testing": ["unit test", "unit tests", "unit testing"],
  "E2E Testing": ["e2e", "end to end testing", "end-to-end"],
  TDD: ["test driven development", "test-driven"],
  Storybook: ["storybook.js", "storybook"],

  // ── Build Tools ──
  Webpack: ["webpack5", "webpack"],
  Vite: ["vitejs", "vite"],
  Rollup: ["rollup"],
  esbuild: ["esbuild"],
  Turbopack: ["turbopack"],
  Turborepo: ["turborepo"],
  "Nx Monorepo": ["nx"],
  Lerna: ["lerna"],
  pnpm: ["pnpm"],
  Bun: ["bun"],
  Deno: ["deno"],

  // ── Auth & Security ──
  OAuth: ["oauth2", "oauth 2.0", "openid connect", "oidc"],
  JWT: ["json web token", "json web tokens"],
  SAML: ["saml"],
  SSO: ["single sign-on", "single sign on"],
  Auth0: ["auth0"],
  Clerk: ["clerk"],
  NextAuth: ["next-auth", "nextauth", "authjs", "auth.js"],
  Passport: ["passportjs", "passport.js"],
  RBAC: ["role-based access", "role based access control"],
  "API Security": ["api key", "api keys", "api security"],

  // ── Message Queues & Streaming ──
  Kafka: ["apache kafka"],
  RabbitMQ: ["rabbitmq", "amqp"],
  "Bull/BullMQ": ["bullmq", "bull queue", "bull"],
  Celery: ["celery"],
  "Apache Pulsar": ["pulsar"],

  // ── AI / ML / Data ──
  "Machine Learning": ["ml", "deep learning", "ai/ml", "machine learning"],
  TensorFlow: ["tensorflow", "tf"],
  PyTorch: ["pytorch"],
  "Scikit-learn": ["sklearn", "scikit-learn", "scikit learn"],
  Pandas: ["pandas"],
  NumPy: ["numpy"],
  Keras: ["keras"],
  OpenCV: ["opencv"],
  "Hugging Face": ["huggingface", "hugging face", "transformers"],
  LangChain: ["langchain"],
  OpenAI: ["openai", "gpt", "chatgpt"],
  "LLM/AI": ["llm", "large language model", "generative ai", "gen ai"],
  "Computer Vision": ["computer vision", "cv"],
  NLP: ["natural language processing", "nlp"],
  "Data Science": ["data science", "data analysis", "data analytics"],
  "Data Engineering": ["data engineering", "data pipeline", "etl"],
  Spark: ["apache spark", "pyspark"],
  Hadoop: ["hadoop", "hdfs", "mapreduce"],
  Airflow: ["apache airflow", "airflow"],
  dbt: ["dbt"],
  Tableau: ["tableau"],
  "Power BI": ["powerbi", "power bi"],
  Looker: ["looker"],
  Jupyter: ["jupyter notebook", "jupyter lab"],

  // ── Mobile ──
  "React Native": ["react native", "react-native"],
  Flutter: ["flutter"],
  "iOS Development": ["ios", "uikit", "swiftui"],
  "Android Development": ["android", "android sdk"],
  Expo: ["expo"],
  Ionic: ["ionic"],
  Capacitor: ["capacitorjs", "capacitor"],

  // ── CMS & E-commerce ──
  WordPress: ["wordpress"],
  Strapi: ["strapi"],
  Contentful: ["contentful"],
  Sanity: ["sanity.io", "sanity"],
  Shopify: ["shopify", "liquid"],
  Magento: ["magento"],
  WooCommerce: ["woocommerce"],

  // ── Payments & SaaS ──
  Stripe: ["stripe api", "stripe"],
  PayPal: ["paypal"],
  Twilio: ["twilio"],
  SendGrid: ["sendgrid"],
  Segment: ["segment"],
  Mixpanel: ["mixpanel"],
  Amplitude: ["amplitude"],

  // ── Design & Collaboration ──
  Figma: ["figma design", "figma"],
  Sketch: ["sketch"],
  "Adobe XD": ["adobe xd", "xd"],
  Photoshop: ["photoshop"],
  Illustrator: ["illustrator"],
  InVision: ["invision"],
  Zeplin: ["zeplin"],

  // ── Project Management ──
  Jira: ["jira software", "jira"],
  Confluence: ["confluence"],
  Linear: ["linear"],
  Notion: ["notion"],
  Trello: ["trello"],
  Asana: ["asana"],
  Monday: ["monday.com"],
  ClickUp: ["clickup"],
  Slack: ["slack"],

  // ── Architecture & Patterns ──
  Microservices: ["micro services", "microservice architecture", "microservices"],
  Serverless: ["serverless architecture", "serverless"],
  "Event-Driven": ["event driven architecture", "event-driven", "eda"],
  "Domain-Driven Design": ["ddd", "domain driven design"],
  CQRS: ["cqrs"],
  "Design Patterns": ["design patterns", "solid principles", "solid"],
  "Clean Architecture": ["clean architecture"],
  "System Design": ["system design"],
  Monorepo: ["monorepo"],

  // ── Linux & OS ──
  Linux: ["ubuntu", "debian", "centos", "rhel", "linux"],

  // ── Blockchain / Web3 ──
  Blockchain: ["web3", "ethereum", "defi", "blockchain"],
  "Smart Contracts": ["smart contract", "smart contracts"],
  Ethers: ["ethers.js", "ethersjs"],
  Hardhat: ["hardhat"],

  // ── Methodologies ──
  Agile: ["agile methodology", "agile"],
  Scrum: ["scrum master", "scrum"],
  Kanban: ["kanban methodology", "kanban"],
  DevOps: ["devops", "site reliability", "sre"],
  "Pair Programming": ["pair programming"],
  "Code Review": ["code review", "peer review"],

  // ── Soft Skills (detected from resume context) ──
  Leadership: ["team lead", "tech lead", "engineering lead", "led a team", "leading"],
  Communication: ["communication skills", "presentation skills", "stakeholder communication"],
  "Problem Solving": ["problem solving", "problem-solving", "analytical skills"],
  Teamwork: ["team player", "cross-functional", "cross functional", "collaboration"],
  "Project Management": ["project management", "project manager"],
  Mentoring: ["mentoring", "mentorship", "coaching"],

  // ── Hosting & Deployment ──
  Vercel: ["vercel"],
  Netlify: ["netlify"],
  Heroku: ["heroku"],
  Render: ["render.com"],
  Railway: ["railway.app", "railway"],
  Fly: ["fly.io"],

  // ── NoSQL Category ──
  NoSQL: ["nosql", "non-relational", "document database"],

  // ── Misc ──
  Regex: ["regular expressions", "regex", "regexp"],
  Markdown: ["markdown"],
  YAML: ["yaml", "yml"],
  JSON: ["json"],
  XML: ["xml"],
  CSV: ["csv"],
};
