export const SKILL_ALIASES: Record<string, string[]> = {
  React: ["reactjs", "react.js", "react js"],
  "Next.js": ["nextjs", "next js", "next.js"],
  "Node.js": ["nodejs", "node js", "node.js"],
  TypeScript: ["typescript", "ts"],
  JavaScript: ["javascript", "js", "ecmascript", "es6", "es2015"],
  Python: ["python3", "py"],
  Java: ["java8", "java11", "java17", "jdk"],
  "C#": ["csharp", "c sharp", "dotnet", "dot net", ".net"],
  "C++": ["cpp", "cplusplus", "c plus plus"],
  Go: ["golang"],
  Rust: ["rustlang"],
  Swift: ["swiftui"],
  Kotlin: ["kotlin"],
  Ruby: ["ruby on rails", "ror"],
  PHP: ["php8", "laravel", "symfony"],
  Vue: ["vuejs", "vue.js", "vue js", "vue3"],
  Angular: ["angularjs", "angular.js", "angular js"],
  Svelte: ["sveltekit", "svelte kit"],
  Docker: ["dockerfile", "docker compose", "docker-compose"],
  Kubernetes: ["k8s", "kube"],
  AWS: ["amazon web services", "amazon aws"],
  Azure: ["microsoft azure", "azure cloud"],
  GCP: ["google cloud", "google cloud platform"],
  PostgreSQL: ["postgres", "psql", "postgresql"],
  MySQL: ["mariadb", "mysql"],
  MongoDB: ["mongo", "mongoose"],
  Redis: ["redis cache"],
  GraphQL: ["graphql", "gql"],
  REST: ["restful", "rest api", "restful api"],
  Git: ["github", "gitlab", "bitbucket"],
  Linux: ["ubuntu", "debian", "centos", "rhel"],
  Terraform: ["tf", "hcl"],
  Jenkins: ["jenkins ci"],
  "CI/CD": ["cicd", "continuous integration", "continuous deployment"],
  Figma: ["figma design"],
  Tailwind: ["tailwindcss", "tailwind css"],
  Redux: ["redux toolkit", "rtk"],
  Express: ["expressjs", "express.js"],
  Django: ["django rest", "drf"],
  Flask: ["flask api"],
  Spring: ["spring boot", "springboot"],
  NestJS: ["nestjs", "nest.js"],
  Prisma: ["prisma orm"],
  SQL: ["structured query language", "t-sql", "pl/sql"],
  NoSQL: ["nosql", "non-relational"],
  TensorFlow: ["tensorflow", "tf"],
  PyTorch: ["pytorch"],
  Pandas: ["pandas"],
  NumPy: ["numpy"],
  Elasticsearch: ["elastic", "elk"],
  RabbitMQ: ["rabbitmq", "amqp"],
  Kafka: ["apache kafka"],
  Nginx: ["nginx"],
  HTML: ["html5"],
  CSS: ["css3", "scss", "sass", "less"],
  Sass: ["scss"],
  Webpack: ["webpack5"],
  Vite: ["vitejs"],
  Jest: ["jest testing"],
  Cypress: ["cypress.io"],
  Playwright: ["playwright testing"],
  Storybook: ["storybook.js"],
  Firebase: ["firestore", "firebase auth"],
  Supabase: ["supabase"],
  Vercel: ["vercel"],
  Netlify: ["netlify"],
  Heroku: ["heroku"],
  Stripe: ["stripe api"],
  OAuth: ["oauth2", "openid connect", "oidc"],
  JWT: ["json web token"],
  WebSocket: ["websockets", "ws", "socket.io"],
  Agile: ["scrum", "kanban methodology"],
  Jira: ["jira software"],
  Solidity: ["solidity", "smart contracts"],
  Blockchain: ["web3", "ethereum", "defi"],
  "Machine Learning": ["ml", "deep learning", "ai/ml"],
  "Data Science": ["data analysis", "data analytics"],
  DevOps: ["site reliability", "sre"],
  Microservices: ["micro services", "microservice architecture"],
  Serverless: ["lambda", "cloud functions"],
};
