const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();
(async () => {
  const total = await p.globalJob.count();
  const withEmail = await p.globalJob.count({ where: { companyEmail: { not: null } } });
  const withHighConf = await p.globalJob.count({ where: { emailConfidence: { gte: 80 } } });
  const withLowConf = await p.globalJob.count({ where: { emailConfidence: { lt: 80 }, companyEmail: { not: null } } });
  const bySource = await p.globalJob.groupBy({ by: ['source'], _count: true, orderBy: { _count: { source: 'desc' } } });
  const emailBySource = await p.globalJob.groupBy({ by: ['source'], where: { companyEmail: { not: null } }, _count: true });
  const emailMethodCounts = await p.globalJob.groupBy({ by: ['emailSource'], where: { emailSource: { not: null } }, _count: true });
  console.log('=== GLOBAL JOB STATS ===');
  console.log('Total jobs:', total);
  console.log('With email:', withEmail, '(' + (withEmail/total*100).toFixed(1) + '%)');
  console.log('High confidence (>=80):', withHighConf);
  console.log('Low confidence (<80):', withLowConf);
  console.log('');
  console.log('=== JOBS BY SOURCE ===');
  bySource.forEach(s => console.log(s.source + ':', s._count));
  console.log('');
  console.log('=== EMAILS BY SOURCE ===');
  emailBySource.forEach(s => console.log(s.source + ':', s._count));
  console.log('');
  console.log('=== EMAIL METHODS ===');
  emailMethodCounts.forEach(s => console.log(s.emailSource + ':', s._count));
  const totalApps = await p.jobApplication.count();
  const sent = await p.jobApplication.count({ where: { status: 'SENT' } });
  const bounced = await p.jobApplication.count({ where: { status: 'BOUNCED' } });
  const draft = await p.jobApplication.count({ where: { status: 'DRAFT' } });
  const ready = await p.jobApplication.count({ where: { status: 'READY' } });
  const failed = await p.jobApplication.count({ where: { status: 'FAILED' } });
  console.log('');
  console.log('=== APPLICATION STATS ===');
  console.log('Total:', totalApps);
  console.log('DRAFT:', draft);
  console.log('READY:', ready);
  console.log('SENT:', sent);
  console.log('BOUNCED:', bounced);
  console.log('FAILED:', failed);
  if (totalApps > 0) console.log('Delivery rate:', (sent/(sent+bounced+failed)*100).toFixed(1) + '%');
  if (sent + bounced > 0) console.log('Bounce rate:', (bounced/(sent+bounced)*100).toFixed(1) + '%');
  const bounces = await p.jobApplication.findMany({ where: { status: 'BOUNCED' }, select: { errorMessage: true, recipientEmail: true }, take: 20 });
  console.log('');
  console.log('=== RECENT BOUNCES (up to 20) ===');
  bounces.forEach(b => console.log(b.recipientEmail, '->', (b.errorMessage || '').substring(0, 80)));
  const sample = await p.globalJob.findMany({ where: { companyEmail: null, description: { not: null } }, select: { description: true, source: true }, take: 200 });
  const emailRegex = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;
  const excluded = new Set(['gmail.com','yahoo.com','hotmail.com','outlook.com','linkedin.com','facebook.com','google.com','example.com','test.com','sentry.io','github.com']);
  let missedEmails = 0;
  let missedSamples = [];
  for (const job of sample) {
    if (!job.description) continue;
    const found = job.description.match(emailRegex) || [];
    const real = found.filter(e => !excluded.has(e.split('@')[1]));
    if (real.length > 0) {
      missedEmails++;
      if (missedSamples.length < 5) missedSamples.push({ source: job.source, emails: real.slice(0, 2) });
    }
  }
  console.log('');
  console.log('=== MISSED EMAIL EXTRACTION (sample of 200 jobs without email) ===');
  console.log('Jobs checked:', sample.length);
  console.log('Had extractable emails:', missedEmails, '(' + (missedEmails/sample.length*100).toFixed(1) + '%)');
  console.log('Samples:', JSON.stringify(missedSamples, null, 2));
  const settings = await p.userSettings.findMany({ select: { sendingPausedUntil: true, smtpSetupDate: true, userId: true } });
  console.log('');
  console.log('=== SENDING STATUS ===');
  settings.forEach(s => {
    const paused = s.sendingPausedUntil && s.sendingPausedUntil > new Date();
    console.log('User:', s.userId.substring(0,8) + '...', 'Paused:', paused ? 'YES until ' + s.sendingPausedUntil : 'No', 'SMTP setup:', s.smtpSetupDate || 'NOT SET');
  });
  await p['']();
})().catch(e => { console.error(e); process.exit(1); });
